version: '3'

services:

    portainer:
        image: portainer/portainer:latest
        ports:
            - "${PORTAINER_PORT}:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:cached
            - ./portainer/:/data:cached
        networks:
            web-net:
                ipv4_address: ${PORTAINER_IP}

    nginx:
        image: nginx:latest
        ports:
            - "${NGINX_80_PORT}:80"
        volumes:
            - ${WORKSPACES}:/data/www/:rw,cached
            - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro,cached
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,cached
            - ./log/nginx/:/var/log/nginx/:rw,cached
        links:
            - php72:fpm72
            - php56:fpm56        
        environment:
            - TZ=Asia/Shanghai
        networks:
            web-net:
                ipv4_address: ${NGINX_IP}       

    php56:
        image: php:5.6-fpm
        expose:
            - "9000"
        volumes:
            - ${WORKSPACES}:/data/www/:rw,cached
            - ./conf/php/php56.ini:/usr/local/etc/php/php.ini:ro,cached
            - ./conf/php/php-fpm.d/www56.conf:/usr/local/etc/php-fpm.d/www.conf:rw,cached
            - ./log/php-fpm/:/var/log/php-fpm/:rw,cached
        links:
            - mysql:mysql
            - redis:redis
        networks:
            web-net:
                ipv4_address: ${PHP56_IP}

    php72:
        image: php:7.2-fpm
        expose:
            - "9000"
        volumes:
            - ${WORKSPACES}:/data/www/:rw,cached
            - ./conf/php/php72.ini:/usr/local/etc/php/php.ini:ro,cached
            - ./conf/php/php-fpm.d/www72.conf:/usr/local/etc/php-fpm.d/www.conf:rw,cached
            - ./log/php-fpm/:/var/log/php-fpm/:rw,cached
        links:
            - mysql:mysql
            - redis:redis
        networks:
            web-net:
                ipv4_address: ${PHP72_IP} 

    mysql:
        image: mysql:5.6
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro,cached
            - ./mysql/:/var/lib/mysql/:rw,cached
            - ./log/mysql/:/var/log/mysql/:rw,cached
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        networks:
            web-net:
                ipv4_address: ${MYSQL_IP}            

    redis:
        image: redis:latest
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            web-net:
                ipv4_address: ${REDIS_IP}

networks:
    web-net:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: "${DOCKER_SUBNET}"            